export const CONFIG = {
  background: "#f7f7ed",
  targetColor: "#B2D89E",
  wallColor: "#C8121D",
  ballColor: "#EBC733",
  platformColor: "#FFFDD0",
  platformFoundColor: "#B2D89E",
  player1Color: "#681037",
  player2Color: "#C8121D",

  platformW: 40,
  platformH: 10,

  targetW: 50,
  targetH: 10,

  ballRadius: 10,

  wallW: 5,

  maxPlatforms: 5,
  renderWalls: false,

  level1: {
    platformMoving: false,
    platformMovingSpeed: 0,
    platformW: 50,
    platformH: 15,
    targetW: 50,
    targetH: 10,
    ballRadius: 10,
    maxPlatforms: 5,
    platformColor: "#FFFDD0",
    platformFoundColor: "#B2D89E",
    player1Color: "#681037",
    player2Color: "#C8121D",
  },
  level2: {
    platformMoving: true,
    platformMovingSpeed: 1,
    platformW: 40,
    platformH: 10,
    targetW: 50,
    targetH: 10,
    ballRadius: 10,
    maxPlatforms: 5,
    platformColor: "#FFFDD0",
    platformFoundColor: "#B2D89E",
    player1Color: "#681037",
    player2Color: "#C8121D",
  },
  level3: {
    platformMoving: true,
    platformMovingSpeed: 2,
    platformW: 40,
    platformH: 10,
    targetW: 30,
    targetH: 10,
    ballRadius: 10,
    maxPlatforms: 5,
    platformColor: "#FFFDD0",
    platformFoundColor: "#B2D89E",
    player1Color: "#681037",
    player2Color: "#C8121D",
  },
};
